### PR TITLE
reworked code for python 3 (3.6) compatibility

### PR DESCRIPTION
**Pull request by ohrstrom**
added some small changes to have `django-sendgrid`playing with python 3.

all tests are still passing (added a new one for py36/dj1.10)

### CODE REVIEW

**Comment by JannKleen** [comment]
Looks great! There seem to be two tox environments failing though...

**Comment by ohrstrom** [comment]
:) i don't know how to configure the .travis.yml to work with multiple python versions in an elegant way...  
like this it works:
https://github.com/resmio/django-sendgrid/pull/12/commits/aec897b89b7943a1d2e24e2af092389805546a76

but this way introduces a bit of redundancy...

**Comment by JannKleen** [comment]
@ohrstrom sorry for the delay on this, I simplified the tox / travis setup a bit and added notes about py3 compatibility to the library

**Comment by ohrstrom** [comment]
kul - thx!

**Comment by JannKleen** [comment]
Thank you for the work you put in!

**Pull request merged**
